'use client';

import { motion, AnimatePresence } from 'motion/react';
export { AnimatePresence };
export const div = motion.div;
export const span = motion.span;
export const section = motion.section;
export const button = motion.button;
export const a = motion.a;
export const img = motion.img;
export const p = motion.p;
export const h1 = motion.h1;
export const h2 = motion.h2;
export const h3 = motion.h3;
export const h4 = motion.h4;
export const h5 = motion.h5;
export const h6 = motion.h6;
export const ul = motion.ul;
export const ol = motion.ol;
export const li = motion.li;
export const table = motion.table;
export const thead = motion.thead;
export const tbody = motion.tbody;
export const tr = motion.tr;
export const th = motion.th;
export const td = motion.td;
export const form = motion.form;