services:
  soniic:
    image: ghcr.io/soniicmusic/soniic:main
    env_file:
      - ./.env
    volumes:
      - ./keys:/app/keys
    st
  db:
    image: postgres:17.5
    env_file:
      - ./.env
    volumes:
      - ./db:/var/lib/postgresql/data