services:
  soniic:
    hostname: soniic
    image: ghcr.io/soniicmusic/soniic:main
    env_file:
      - ./.env
    volumes:
      - ./keys:/app/keys
    deploy:
      update_config:
        order: start-first
    depends_on:
      - db
    networks:
      - soniic
  db:
    image: postgres:18.1
    env_file:
      - ./.env
    volumes:
      - ./db:/var/lib/postgresql/data
  cloudflared:
      image: cloudflare/cloudflared:latest
      command: tunnel --no-autoupdate run --token
        ${CLOUDFLARED_TOKEN}
      env_file:
        - ./.env
      networks:
        - soniic
networks:
  soniic: