name: Build Next.js App
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: pnpm install

      - name: Build the Next.js app
        run: pnpm run build
